
= Sliconf Micro =

Sliconf uygulamasının backend kısmı

== Kurulum ==
Linkteki dosyaları bilgisayara indiriyoruz:
https://github.com/altuga/sliconf-micro

Dosyaları almakta sıkıntı yaşanırsa bu yöntemlerle  indirebilirsiniz

Windows:
https://stackoverflow.com/questions/6466945/fastest-way-to-download-a-github-project
yada
https://help.github.com/articles/cloning-a-repository/

Linux:
https://help.github.com/articles/cloning-a-repository/#platform-linux

Mac:
https://help.github.com/articles/cloning-a-repository/#platform-mac


=== Jdk kurulumu:
Gerekli bilgilar bu linkte:
http://docs.oracle.com/javase/7/docs/webnotes/install/index.html

=== Intellij IDEA kurulumu

Buradan sisteme göre gerekli dosyaları indiriyoruz:
https://www.jetbrains.com/idea/download/#section=windows 

Kurulum için gerekli bilgiler burada:
https://www.jetbrains.com/help/idea/installing-and-launching.html 

=== Properties Dosyaları Düzenlenmesi
src/main/resources dizini içerisindeki .example uzantılı dosyalar, .properties uzantısı haline getirilip dosya içerisindeki "<example-tag>" formatındaki alanlar yorum satırlarındaki yönergelere göre düzenlenmelidir.


=== Postman

Chromeun Postman eklentisi deneme amaçlı POST/GET vb istekleri göndermek için bir eklentidir.Kullanım  sistemin çalışması için gerekli değildir.
https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop?hl=en

Gerekli routeların kontrolü için bu link size yardımcı olacaktır.Sadece chromeda çalışır.
https://www.getpostman.com/collections/dae7508c1fe7667f32bd


## MongoDB

Lokalde mongo sunucusu kurulduktan sonra aşağıdaki adımlarla ayağa kaldırılması gerekiyor.

### Yetkilendirme

MongoDB, yetkilendirme aktifleştirilerek ayağa kaldırılmalı. Windows için:

```
$mongod --dbpath dataPath --auth
```

### Yetkilendirilmiş Kullanıcı Oluşturulması

Mongo Shell'e yetkilendirilmiş kullanıcı girişi için projedekiyle benzer isim, şifre ve role sahip bir kullanıcı eklenmesi gerekiyor:

```
$mongo
use admin
db.createUser({user: "sliconfSecretUser", pwd: "<providedPassword>", roles:[{role: "root", db: "admin"}]})
```

Komut, aşağıdakine benzer bir çıktı döndürmeli
```
Successfully added user: {
	"user" : "sliconfSecretUser",
	"roles" : [
		{
			"role" : "root",
			"db" : "admin"
		}
	]
}
```

### Mongo Shell'e Giriş
```
mongo -u sliconfSecretUser --authenticationDatabase admin -p
```

